### ISSUE TITLE
Login successful, but streams not working

### ISSUE THREAD

**Issue by tomx101cz** [goodbyepavlyi/o2tv-iptvserver#4]
I am able to login and pull the playlist, but unable to play any of the stream using my end devices. I tried VLC, Channels DVR, Safari browser, TVHeadEnd.

Is this approach still working?

**Comment by havran99** [comment]
Yes, it works without problems, now tested.

**Comment by goodbyepavlyi** [comment]
Hello, I've just tried playing a stream in VLC, and everything appears to be functioning properly on my side. Are you seeing any errors in the application logs? If you are, could you please share them here?

**Comment by tomx101cz** [comment]
No errors in the application log, just a confirmation that the end device is accessing the stream, e.g.:
`(Info) WebServer - 10.10.10.6 - "GET /api/o2tv/stream?id=1254235&md=188173007 http" 200 - Go-http-client/1.1`

This is the log I am getting in Channels DVR:
2024/02/27 12:07:19.500506 [HLS] ffmpeg: ch10054-dANY-ip192.168.0.1-remux:  Output file #0 does not contain any stream
2024/02/27 12:07:19.518061 [HLS] Couldn't generate stream playlist for ch10054-dANY-ip192.168.0.1: Stream stopped
2024/02/27 12:07:19.519150 [HLS] Stopping transcoder session ch10054-dANY-ip192.168.0.1

TVHeadend throws similar errors:
2024-02-27 21:11:28.002 mpegts: playlist - Premier Sport 3 HD in O2TV NEW - scan no data, failed

Any ideas?

**Comment by goodbyepavlyi** [comment]
It's strange that when I attempt to play the identical multi-dimensional stream, it functions as expected for me. Can you delete the application data to see if this resolves the issue and prompts you to log in again?

**Comment by tomx101cz** [comment]
I tried that, still the same problem. Based on everything I can see, the login is successful, the playlist is generated, but starting the stream does not work well. I am on the prepaid Sport Premium package and it was migrated to O2TV 2.0 today, so I wonder if that's causing some issues on their end. The iOS app was throwing all sorts of login errors earlier today, so maybe the backend is not fully synced yet. I will try again in a few days.

**Comment by goodbyepavlyi** [comment]
> I tried that, still the same problem. Based on everything I can see, the login is successful, the playlist is generated, but starting the stream does not work well. I am on the prepaid Sport Premium package and it was migrated to O2TV 2.0 today, so I wonder if that's causing some issues on their end. The iOS app was throwing all sorts of login errors earlier today, so maybe the backend is not fully synced yet. I will try again in a few days.

It's possible that your account migration to version 2.0 hasn't fully completed, potentially explaining the streaming issues you're experiencing. Given that both @havran99 and I have no trouble with streaming, it seems unlikely that the code itself is the problem. I'll keep the issue open, and if the problem persists after a few days, please notify me. In that case, I'll continue working to find a solution.

**Comment by tomx101cz** [comment]
I got it working using VLC, no issues there. It was probably something with the O2 servers.

I am still having issues with TVHeadend and Channels DVR. I think they are not able to interpret the MPEG-DASH stream. I will probably need to remux everything using FFMPEG into MPEG TS stream.

**Comment by goodbyepavlyi** [comment]
I am using only VLC for testing since it's working for me always but I'm not sure about other applications.

**Comment by tomx101cz** [comment]
It took some tweaking, but it's possible to get the stream into TVHeadend using pipe. Here is the solution if anyone comes across the same issue:
`pipe:///usr/bin/env streamlink --locale cs_CZ  dash://http://ip:3999/api/o2tv/stream?id=1254963 best --stdout --ffmpeg-fout "mpegts"`
